# Generated by Django 4.2.7 on 2025-10-12 17:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("intelligent_import", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="schematemplate",
            name="unique_template_version",
        ),
        migrations.RenameIndex(
            model_name="datalineage",
            new_name="intelligent_import__f837a0_idx",
            old_name="ii_lineage_session_table_idx",
        ),
        migrations.RenameIndex(
            model_name="datalineage",
            new_name="intelligent_target__d1508c_idx",
            old_name="ii_lineage_target_idx",
        ),
        migrations.RenameIndex(
            model_name="datalineage",
            new_name="intelligent_is_roll_375ece_idx",
            old_name="ii_lineage_rollback_idx",
        ),
        migrations.RenameIndex(
            model_name="importsession",
            new_name="intelligent_user_id_b847e7_idx",
            old_name="ii_sess_user_status_idx",
        ),
        migrations.RenameIndex(
            model_name="importsession",
            new_name="intelligent_file_ha_f65ad6_idx",
            old_name="ii_sess_file_hash_idx",
        ),
        migrations.RenameIndex(
            model_name="importsession",
            new_name="intelligent_created_7d1328_idx",
            old_name="ii_sess_created_idx",
        ),
        migrations.RenameIndex(
            model_name="schemaauditlog",
            new_name="intelligent_import__5e2f0d_idx",
            old_name="ii_audit_session_action_idx",
        ),
        migrations.RenameIndex(
            model_name="schemaauditlog",
            new_name="intelligent_table_n_33e606_idx",
            old_name="ii_audit_table_idx",
        ),
        migrations.RenameIndex(
            model_name="schemaauditlog",
            new_name="intelligent_created_d1a79a_idx",
            old_name="ii_audit_created_idx",
        ),
        migrations.AlterUniqueTogether(
            name="schematemplate",
            unique_together={("name", "version")},
        ),
    ]
