# Generated by Django 4.2.7 on 2025-10-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "intelligent_import",
            "0002_remove_schematemplate_unique_template_version_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="importsession",
            name="analysis_summary",
            field=models.JSONField(
                default=dict, help_text="Key results from the schema analyzer"
            ),
        ),
    ]
