# Generated by Django 4.2.7 on 2025-10-15 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("intelligent_import", "0003_importsession_analysis_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("data_insert", "Insert Data"),
                            ("data_update", "Update Data"),
                            ("master_data_create", "Create Master Data"),
                            ("import_rollback", "Rollback Import"),
                        ],
                        max_length=20,
                    ),
                ),
                ("table_name", models.CharField(max_length=100)),
                (
                    "details",
                    models.TextField(
                        help_text="Details of the action, e.g., SQL statement or summary"
                    ),
                ),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("affected_rows", models.IntegerField(default=0)),
                ("execution_time_ms", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_import_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "intelligent_import_audit_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MasterDataCandidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_master_table",
                    models.CharField(help_text="e.g., mis_app_buyer", max_length=100),
                ),
                (
                    "proposed_value",
                    models.CharField(
                        help_text="The new value from the file (e.g., a new buyer name)",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewer_comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "intelligent_import_master_data_candidates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name (e.g., 'Export Order Report')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Detailed description"),
                ),
                (
                    "ownership_type",
                    models.CharField(
                        choices=[
                            ("personal", "Personal Template"),
                            ("team", "Team Template"),
                            ("global", "Global Template"),
                        ],
                        default="team",
                        max_length=20,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(default=1, help_text="Template version"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "filename_patterns",
                    models.JSONField(
                        default=list,
                        help_text="Patterns to auto-detect this template from filenames",
                    ),
                ),
                (
                    "header_patterns",
                    models.JSONField(
                        default=list,
                        help_text="Header patterns to identify this report type",
                    ),
                ),
                (
                    "target_table",
                    models.CharField(
                        help_text="e.g., mis_app_sewingproduction", max_length=100
                    ),
                ),
                (
                    "column_mapping",
                    models.JSONField(
                        default=dict,
                        help_text="Mapping from file columns to target_table fields",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_report_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_report_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "intelligent_import_report_templates",
                "ordering": ["-created_at"],
                "unique_together": {("name", "version")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="schematemplate",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="schematemplate",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="schematemplate",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="importsession",
            name="created_tables",
        ),
        migrations.RemoveField(
            model_name="importsession",
            name="final_schema",
        ),
        migrations.RemoveField(
            model_name="importsession",
            name="proposed_schema",
        ),
        migrations.RemoveField(
            model_name="importsession",
            name="schema_template",
        ),
        migrations.AlterField(
            model_name="importsession",
            name="analysis_summary",
            field=models.JSONField(
                default=dict, help_text="Key results from the file analyzer"
            ),
        ),
        migrations.AlterField(
            model_name="importsession",
            name="column_mapping",
            field=models.JSONField(
                default=dict,
                help_text="File columns to schema fields mapping for this session",
            ),
        ),
        migrations.AlterField(
            model_name="importsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("file_uploaded", "File Uploaded"),
                    ("analyzing", "Analyzing File"),
                    ("template_suggested", "Template Suggested"),
                    ("mapping_defined", "Column Mapping Defined"),
                    ("mapping_approved", "Mapping Approved"),
                    ("data_validated", "Data Validated"),
                    ("pending_approval", "Pending Final Approval"),
                    ("approved", "Approved for Import"),
                    ("importing_data", "Importing Data"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("rolled_back", "Rolled Back"),
                ],
                default="file_uploaded",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="SchemaAuditLog",
        ),
        migrations.DeleteModel(
            name="SchemaTemplate",
        ),
        migrations.AddField(
            model_name="masterdatacandidate",
            name="import_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="master_data_candidates",
                to="intelligent_import.importsession",
            ),
        ),
        migrations.AddField(
            model_name="masterdatacandidate",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="importauditlog",
            name="import_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="import_audit_logs",
                to="intelligent_import.importsession",
            ),
        ),
        migrations.AddField(
            model_name="importauditlog",
            name="report_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="intelligent_import.reporttemplate",
            ),
        ),
        migrations.AddField(
            model_name="importsession",
            name="report_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="intelligent_import.reporttemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="masterdatacandidate",
            index=models.Index(
                fields=["import_session", "status"],
                name="intelligent_import__6e7fcb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="masterdatacandidate",
            index=models.Index(
                fields=["target_master_table"], name="intelligent_target__54e12a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importauditlog",
            index=models.Index(
                fields=["import_session", "action"],
                name="intelligent_import__00ddf5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="importauditlog",
            index=models.Index(
                fields=["table_name"], name="intelligent_table_n_e59ce7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importauditlog",
            index=models.Index(
                fields=["created_at"], name="intelligent_created_29b6e7_idx"
            ),
        ),
    ]
