# Generated by Django 4.2.7 on 2025-10-16 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "intelligent_import",
            "0004_importauditlog_masterdatacandidate_reporttemplate_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("unit_name_alias", models.CharField(max_length=255, unique=True)),
                ("unit_code", models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterModelOptions(
            name="reporttemplate",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="reporttemplate",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="reporttemplate",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rt_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reporttemplate",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="reporttemplate",
            name="filename_patterns",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="reporttemplate",
            name="header_patterns",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="reporttemplate",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="reporttemplate",
            name="ownership_type",
            field=models.CharField(
                choices=[("team", "Team"), ("private", "Private")],
                default="team",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="reporttemplate",
            name="target_table",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="reporttemplate",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rt_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reporttemplate",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterModelTable(
            name="reporttemplate",
            table=None,
        ),
        migrations.CreateModel(
            name="PendingMaster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity",
                    models.CharField(
                        choices=[
                            ("units", "Units"),
                            ("buyers", "Buyers"),
                            ("styles", "Styles"),
                            ("lines", "Lines"),
                            ("vendors", "Vendors"),
                            ("colors", "Colors"),
                            ("airports", "Airports"),
                        ],
                        max_length=32,
                    ),
                ),
                ("payload", models.JSONField()),
                ("status", models.CharField(default="pending", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="reporttemplate",
            name="column_mapping",
        ),
        migrations.CreateModel(
            name="ReportTemplateHeader",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_header", models.CharField(max_length=255)),
                ("target_table", models.CharField(blank=True, max_length=255)),
                ("target_column", models.CharField(blank=True, max_length=255)),
                ("data_type", models.CharField(blank=True, max_length=64)),
                ("is_required", models.BooleanField(default=False)),
                ("default_value", models.CharField(blank=True, max_length=255)),
                ("master_data_source", models.CharField(blank=True, max_length=64)),
                ("master_output_field", models.CharField(blank=True, max_length=64)),
                ("strict", models.BooleanField(default=False)),
                ("depends_on", models.JSONField(blank=True, default=list)),
                ("transform", models.CharField(blank=True, max_length=128)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="headers",
                        to="intelligent_import.reporttemplate",
                    ),
                ),
            ],
            options={
                "unique_together": {("template", "source_header")},
            },
        ),
    ]
