# Generated by Django 4.2.7 on 2025-10-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intelligent_import", "0005_unitalias_alter_reporttemplate_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importsession",
            name="import_progress",
            field=models.IntegerField(default=0),
        ),
    ]
