# Generated by Django 4.2.7 on 2025-10-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intelligent_import", "0006_importsession_import_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="reporttemplate",
            name="fields",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="reporttemplate",
            name="mapping",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="reporttemplate",
            name="schema_proposals",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
