# Generated by Django 4.2.7 on 2025-10-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "intelligent_import",
            "0007_reporttemplate_fields_reporttemplate_mapping_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="importsession",
            name="import_mode",
            field=models.CharField(blank=True, default="auto", max_length=20),
        ),
        migrations.AddField(
            model_name="importsession",
            name="target_table",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
