# Generated by Django 4.2.7 on 2025-09-25 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("mis_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardVersionHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                (
                    "config_snapshot",
                    models.JSONField(
                        help_text="A JSON snapshot of the dashboard's config_v2 at this version."
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="version_history",
                        to="mis_app.dashboard",
                    ),
                ),
                (
                    "saved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who saved this version.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Version History",
                "verbose_name_plural": "Dashboard Version Histories",
                "ordering": ["-saved_at"],
                "unique_together": {("dashboard", "version_number")},
            },
        ),
    ]
