# Generated by Django 4.2.7 on 2025-09-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mis_app", "0002_dashboardversionhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
