# Generated by Django 4.2.7 on 2025-09-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mis_app", "0003_notification_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="related_object_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_object_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
