# Generated by Django 4.2.7 on 2025-09-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mis_app", "0004_notification_related_object_id_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userpermission",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="grouppermission",
            name="permission_level",
            field=models.CharField(
                choices=[
                    ("none", "No Access"),
                    ("view", "View Only"),
                    ("upload", "Upload Only"),
                    ("edit", "Edit"),
                    ("admin", "Full Admin"),
                ],
                default="view",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userpermission",
            name="permission_level",
            field=models.CharField(
                choices=[
                    ("none", "No Access"),
                    ("view", "View Only"),
                    ("upload", "Upload Only"),
                    ("edit", "Edit"),
                    ("admin", "Full Admin"),
                ],
                default="view",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="userpermission",
            constraint=models.UniqueConstraint(
                fields=("user", "resource_type", "resource_id", "permission_level"),
                name="uniq_userperm_by_resource_and_level",
            ),
        ),
        migrations.AlterModelTable(
            name="userpermission",
            table=None,
        ),
    ]
