# Generated by Django 4.2.7 on 2025-09-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mis_app", "0005_alter_userpermission_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userpermission",
            name="uniq_userperm_by_resource_and_level",
        ),
        migrations.AlterField(
            model_name="grouppermission",
            name="permission_level",
            field=models.CharField(
                choices=[
                    ("none", "No Access"),
                    ("view", "View Only"),
                    ("edit", "Edit"),
                    ("admin", "Full Admin"),
                ],
                default="view",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userpermission",
            name="permission_level",
            field=models.CharField(
                choices=[
                    ("none", "No Access"),
                    ("view", "View Only"),
                    ("edit", "Edit"),
                    ("admin", "Full Admin"),
                ],
                default="view",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userpermission",
            unique_together={("user", "resource_type", "resource_name")},
        ),
        migrations.AlterModelTable(
            name="userpermission",
            table="user_permissions",
        ),
    ]
