# Generated by Django 4.2.7 on 2025-09-27 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "mis_app",
            "0006_remove_userpermission_uniq_userperm_by_resource_and_level_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="canvaslayout",
            name="collapsed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="canvaslayout",
            name="connection",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="canvas_layouts",
                to="mis_app.externalconnection",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="canvaslayout",
            name="table_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="canvaslayout",
            name="x_pos",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="canvaslayout",
            name="y_pos",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="connectionjoin",
            name="cardinality",
            field=models.CharField(
                choices=[
                    ("one-to-one", "One-to-One (1:1)"),
                    ("one-to-many", "One-to-Many (1:N)"),
                    ("many-to-one", "Many-to-One (N:1)"),
                    ("many-to-many", "Many-to-Many (N:M)"),
                ],
                default="one-to-many",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="canvaslayout",
            unique_together={("connection", "table_name")},
        ),
        migrations.RemoveField(
            model_name="canvaslayout",
            name="dashboard",
        ),
        migrations.RemoveField(
            model_name="canvaslayout",
            name="layout_data",
        ),
    ]
