# Generated by Django 4.2.7 on 2025-09-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mis_app", "0007_canvaslayout_collapsed_canvaslayout_connection_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dashboarddatacontext",
            options={
                "verbose_name": "Dashboard Data Context",
                "verbose_name_plural": "Dashboard Data Contexts",
            },
        ),
        migrations.AddField(
            model_name="dashboarddatacontext",
            name="connection_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="UUID of the external connection configured for this dashboard.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dashboarddatacontext",
            name="joins",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of join specifications among selected tables.",
            ),
        ),
        migrations.AddField(
            model_name="dashboarddatacontext",
            name="selected_tables",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of table names selected in the data context.",
            ),
        ),
        migrations.AlterField(
            model_name="dashboarddatacontext",
            name="context_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="(Legacy) Arbitrary JSON blob for the data context. Kept for backward compatibility; new code should use first-class fields.",
            ),
        ),
        migrations.AddIndex(
            model_name="dashboarddatacontext",
            index=models.Index(
                fields=["dashboard"], name="dashboard_d_dashboa_e8a978_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dashboarddatacontext",
            index=models.Index(
                fields=["connection_id"], name="dashboard_d_connect_8e35bf_idx"
            ),
        ),
    ]
