# Generated by Django 4.2.7 on 2025-09-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mis_app", "0008_alter_dashboarddatacontext_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboarddatacontext",
            name="calculated_fields",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of calculated fields: [{'name', 'formula', 'aggregation'}].",
            ),
        ),
    ]
