# Generated by Django 4.2.7 on 2025-10-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mis_app", "0009_dashboarddatacontext_calculated_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="default_database",
            field=models.CharField(
                blank=True,
                help_text="Default database connection",
                max_length=50,
                null=True,
            ),
        ),
    ]
