# Generated by Django 4.2.7 on 2025-10-18 08:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mis_app", "0010_make_default_database_nullable"),
    ]

    operations = [
        migrations.RunSQL("UPDATE users SET default_database = NULL"),
    ]
