# Generated by Django 4.2.7 on 2025-10-18 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mis_app", "0011_set_default_database_to_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="default_database",
            field=models.ForeignKey(
                blank=True,
                help_text="Default database connection",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mis_app.externalconnection",
            ),
        ),
    ]
